-- MySQL Script generated by MySQL Workbench
-- mar 25 ago 2020 00:48:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recancheros_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `recancheros_bd` ;

-- -----------------------------------------------------
-- Schema recancheros_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recancheros_bd` DEFAULT CHARACTER SET utf8 ;
USE `recancheros_bd` ;

-- -----------------------------------------------------
-- Table `recancheros_bd`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`rol` (
  `rol_id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`tipo_documento` (
  `id_tipo_documento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`usuario` (
  `id` INT NOT NULL auto_increment,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `numcel` VARCHAR(11) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contra` VARCHAR(45) NOT NULL,
  `numidentificacion` VARCHAR(15) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT "A",
  `rol_rol_id` INT NOT NULL DEFAULT 3,
  `tipo_documento_id_tipo_documento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuenta_rol1_idx` (`rol_rol_id` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_documento1_idx` (`tipo_documento_id_tipo_documento` ASC) VISIBLE,
  CONSTRAINT `fk_cuenta_rol1`
    FOREIGN KEY (`rol_rol_id`)
    REFERENCES `recancheros_bd`.`rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id_tipo_documento`)
    REFERENCES `recancheros_bd`.`tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`menu` (
  `menu_id` INT NOT NULL,
  `menu_nombre` VARCHAR(45) NOT NULL,
  `menu_padre` VARCHAR(1) NOT NULL,
  `menu_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`centro_deportivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`centro_deportivo` (
  `cendeportivo_id` INT NOT NULL,
  `cendeportivo_nombre` VARCHAR(45) NOT NULL,
  `cendeportivo_direccion` VARCHAR(45) NOT NULL,
  `cendeportivo_correo` VARCHAR(45) NOT NULL,
  `cendeportivo_tel` VARCHAR(15) NULL,
  `cendeportivo_rut` VARCHAR(35) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`cendeportivo_id`),
  INDEX `fk_centro_deportivo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_centro_deportivo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `recancheros_bd`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`tipo_cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`tipo_cancha` (
  `tipo_cancha_id` INT NOT NULL,
  `tipo_cancha_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_cancha_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`cancha` (
  `cancha_id` INT NOT NULL,
  `cancha_nombre` VARCHAR(45) NOT NULL,
  `cancha_numero` VARCHAR(2) NOT NULL,
  `tipo_cancha_tipo_cancha_id` INT NOT NULL,
  `centro_deportivo_cendeportivo_id` INT NOT NULL,
  PRIMARY KEY (`cancha_id`),
  INDEX `fk_cancha_tipo_cancha1_idx` (`tipo_cancha_tipo_cancha_id` ASC) VISIBLE,
  INDEX `fk_cancha_centro_deportivo1_idx` (`centro_deportivo_cendeportivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancha_tipo_cancha1`
    FOREIGN KEY (`tipo_cancha_tipo_cancha_id`)
    REFERENCES `recancheros_bd`.`tipo_cancha` (`tipo_cancha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cancha_centro_deportivo1`
    FOREIGN KEY (`centro_deportivo_cendeportivo_id`)
    REFERENCES `recancheros_bd`.`centro_deportivo` (`cendeportivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`horario_disponible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`horario_disponible` (
  `horario_id` INT NOT NULL,
  `hora_inicio` DATETIME NOT NULL,
  `hora_finaliza` DATETIME NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`horario_id`),
  INDEX `fk_horario_disponible_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_horario_disponible_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `recancheros_bd`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`horario_disponible_has_cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`horario_disponible_has_cancha` (
  `horario_disponible_horario_id` INT NOT NULL,
  `cancha_cancha_id` INT NOT NULL,
  `precio` INT NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`horario_disponible_horario_id`, `cancha_cancha_id`),
  INDEX `fk_horario_disponible_has_cancha_cancha1_idx` (`cancha_cancha_id` ASC) VISIBLE,
  INDEX `fk_horario_disponible_has_cancha_horario_disponible1_idx` (`horario_disponible_horario_id` ASC) VISIBLE,
  CONSTRAINT `fk_horario_disponible_has_cancha_horario_disponible1`
    FOREIGN KEY (`horario_disponible_horario_id`)
    REFERENCES `recancheros_bd`.`horario_disponible` (`horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_disponible_has_cancha_cancha1`
    FOREIGN KEY (`cancha_cancha_id`)
    REFERENCES `recancheros_bd`.`cancha` (`cancha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`numero_celular_centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`numero_celular_centro` (
  `idnumero_celular_centro` INT NOT NULL,
  `numero_celular_centro` VARCHAR(15) NOT NULL,
  `centro_deportivo_cendeportivo_id` INT NOT NULL,
  PRIMARY KEY (`idnumero_celular_centro`),
  INDEX `fk_numero_celular_centro_centro_deportivo1_idx` (`centro_deportivo_cendeportivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_numero_celular_centro_centro_deportivo1`
    FOREIGN KEY (`centro_deportivo_cendeportivo_id`)
    REFERENCES `recancheros_bd`.`centro_deportivo` (`cendeportivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`servicio` (
  `servicio_id` INT NOT NULL,
  `servicio_nombre` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`servicio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`menu_has_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`menu_has_rol` (
  `menu_menu_id` INT NOT NULL,
  `rol_rol_id` INT NOT NULL,
  PRIMARY KEY (`menu_menu_id`, `rol_rol_id`),
  INDEX `fk_menu_has_rol_rol1_idx` (`rol_rol_id` ASC) VISIBLE,
  INDEX `fk_menu_has_rol_menu1_idx` (`menu_menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_menu_has_rol_menu1`
    FOREIGN KEY (`menu_menu_id`)
    REFERENCES `recancheros_bd`.`menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_has_rol_rol1`
    FOREIGN KEY (`rol_rol_id`)
    REFERENCES `recancheros_bd`.`rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`usuario_has_cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`usuario_has_cancha` (
  `usuario_id` INT NOT NULL,
  `cancha_cancha_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `cancha_cancha_id`),
  INDEX `fk_usuario_has_cancha_cancha1_idx` (`cancha_cancha_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_cancha_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_cancha_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `recancheros_bd`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_cancha_cancha1`
    FOREIGN KEY (`cancha_cancha_id`)
    REFERENCES `recancheros_bd`.`cancha` (`cancha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`deporte` (
  `deporte_id` INT NOT NULL,
  `deporte_nombre` VARCHAR(45) NOT NULL,
  `deporte_estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`deporte_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`centro_deportivo_has_deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`centro_deportivo_has_deporte` (
  `centro_deportivo_cendeportivo_id` INT NOT NULL,
  `deporte_deporte_id` INT NOT NULL,
  PRIMARY KEY (`centro_deportivo_cendeportivo_id`, `deporte_deporte_id`),
  INDEX `fk_centro_deportivo_has_deporte_deporte1_idx` (`deporte_deporte_id` ASC) VISIBLE,
  INDEX `fk_centro_deportivo_has_deporte_centro_deportivo1_idx` (`centro_deportivo_cendeportivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_centro_deportivo_has_deporte_centro_deportivo1`
    FOREIGN KEY (`centro_deportivo_cendeportivo_id`)
    REFERENCES `recancheros_bd`.`centro_deportivo` (`cendeportivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centro_deportivo_has_deporte_deporte1`
    FOREIGN KEY (`deporte_deporte_id`)
    REFERENCES `recancheros_bd`.`deporte` (`deporte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recancheros_bd`.`centro_deportivo_has_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recancheros_bd`.`centro_deportivo_has_servicio` (
  `centro_deportivo_cendeportivo_id` INT NOT NULL,
  `servicio_servicio_id` INT NOT NULL,
  PRIMARY KEY (`centro_deportivo_cendeportivo_id`, `servicio_servicio_id`),
  INDEX `fk_centro_deportivo_has_servicio_servicio1_idx` (`servicio_servicio_id` ASC) VISIBLE,
  INDEX `fk_centro_deportivo_has_servicio_centro_deportivo1_idx` (`centro_deportivo_cendeportivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_centro_deportivo_has_servicio_centro_deportivo1`
    FOREIGN KEY (`centro_deportivo_cendeportivo_id`)
    REFERENCES `recancheros_bd`.`centro_deportivo` (`cendeportivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centro_deportivo_has_servicio_servicio1`
    FOREIGN KEY (`servicio_servicio_id`)
    REFERENCES `recancheros_bd`.`servicio` (`servicio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
